### ISSUE TITLE
error with selectattr & rejectattr filters containing an expression test arguments.

### ISSUE THREAD

**Issue by ndwilliams3** [HubSpot/prettier-plugin-hubl#72] opened 2023-06-20 15:17 UTC
getting error when using a filter with multiple arguments.

`{% set selected_items = dict_var|selectattr("size", "equalto", "L") %}`

Error: unexpected token: ,
    at new TemplateError (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/lib.js:68:23)
    at Parser.error (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:57:16)
    at Parser.parsePrimary (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:923:24)
    at Parser.parseUnary (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:866:25)
    at Parser.parsePow (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:849:25)
    at Parser.parseMod (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:841:25)
    at Parser.parseFloorDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:833:25)
    at Parser.parseDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:825:25)
    at Parser.parseMul (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:817:25)
    at Parser.parseSub (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:809:25)
    at Parser.parseAdd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:801:25)
    at Parser.parseConcat (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:793:25)
    at Parser.parseCompare (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:770:27)
    at Parser.parseIs (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:757:25)
    at Parser.parseIn (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:730:25)
    at Parser.parseNot (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:727:21)
    at Parser.parseAnd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:715:25)
    at Parser.parseOr (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:706:25)
    at Parser.parseInlineIf (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:689:25)
    at Parser.parseExpression (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:675:25)
    at Parser.parsePostfix (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:665:119)
    at Parser.parsePrimary (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:917:25)
    at Parser.parseUnary (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:866:25)
    at Parser.parsePow (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:849:25)
    at Parser.parseMod (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:841:25)
    at Parser.parseFloorDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:833:25)
    at Parser.parseDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:825:25)
    at Parser.parseMul (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:817:25)
    at Parser.parseSub (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:809:25)
    at Parser.parseAdd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:801:25)
    at Parser.parseConcat (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:793:25)
    at Parser.parseCompare (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:770:27)
    at Parser.parseIs (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:757:25)
    at Parser.parseIn (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:730:25)
    at Parser.parseNot (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:727:21)
    at Parser.parseAnd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:715:25)
    at Parser.parseOr (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:706:25)
    at Parser.parseInlineIf (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:689:25)
    at Parser.parseExpression (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:675:25)
    at Parser.parseSignature (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:1042:34)
    at Parser.parsePostfix (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:646:76)
    at Parser.parseFilterArgs (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:936:31)
    at Parser.parseFilter (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:948:131)
    at Parser.parseUnary (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:869:25)
    at Parser.parsePow (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:849:25)
    at Parser.parseMod (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:841:25)
    at Parser.parseFloorDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:833:25)
    at Parser.parseDiv (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:825:25)
    at Parser.parseMul (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:817:25)
    at Parser.parseSub (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:809:25)
    at Parser.parseAdd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:801:25)
    at Parser.parseConcat (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:793:25)
    at Parser.parseCompare (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:770:27)
    at Parser.parseIs (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:757:25)
    at Parser.parseIn (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:730:25)
    at Parser.parseNot (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:727:21)
    at Parser.parseAnd (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:715:25)
    at Parser.parseOr (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:706:25)
    at Parser.parseInlineIf (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:689:25)
    at Parser.parseExpression (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:675:25)
    at Parser.parseSet (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:487:31)
    at Parser.parseStatement (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:565:29)
    at Parser.parseNodes (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:1076:32)
    at Parser.parseAsRoot (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:1106:42)
    at parse (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/parser/parser.js:1115:18)
    at Object.parse (node_modules/@hubspot/prettier-plugin-hubl/parser/dist/index.js:11:12)

**Comment by j-malt** [comment] 2024-05-07 21:05
Hi @ndwilliams3. I'm not able to reproduce this issue with the string `{% set selected_items = dict_var|selectattr("size", "equalto", "L") %}`. It is formatting correctly for me. Going to close the issue since it's quite old, but feel free to reopen with a larger snippet that is causing the error if you can still reproduce on `v0.2.5+` of the plugin

**Closed by j-malt** 2024-05-07 21:05 UTC
Labels: bug
